"""Initial commit with all tables

Revision ID: a2c975fd7e67
Revises: 
Create Date: 2026-08-05 19:37:43.313093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c975fd7e67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('uid', sa.String(length=7), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index('ix_metadata_expires_at', 'metadata', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.String(length=6), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_push_subscriptions_user_revoked', 'push_subscriptions', ['user_uid', 'revoked_at'], unique=False)
    op.create_index('ux_push_subscriptions_endpoint', 'push_subscriptions', ['endpoint'], unique=True)
    op.create_table('shortcut_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.String(length=6), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shortcut_keys_user_revoked', 'shortcut_keys', ['user_uid', 'revoked_at'], unique=False)
    op.create_table('video_sessions',
    sa.Column('uid', sa.String(length=8), nullable=False),
    sa.Column('user_uid', sa.String(length=6), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='status'), nullable=False),
    sa.Column('metadata_uid', sa.String(length=7), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['metadata_uid'], ['metadata.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_video_sessions_expires_at', 'video_sessions', ['expires_at'], unique=False)
    op.create_index('ix_video_sessions_metadata_uid', 'video_sessions', ['metadata_uid'], unique=False)
    op.create_index('ix_video_sessions_status_created', 'video_sessions', ['status', 'created_at'], unique=False)
    op.create_index('ix_video_sessions_user_video_expires', 'video_sessions', ['user_uid', 'video_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_sessions_user_video_expires', table_name='video_sessions')
    op.drop_index('ix_video_sessions_status_created', table_name='video_sessions')
    op.drop_index('ix_video_sessions_metadata_uid', table_name='video_sessions')
    op.drop_index('ix_video_sessions_expires_at', table_name='video_sessions')
    op.drop_table('video_sessions')
    op.drop_index('ix_shortcut_keys_user_revoked', table_name='shortcut_keys')
    op.drop_table('shortcut_keys')
    op.drop_index('ux_push_subscriptions_endpoint', table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_user_revoked', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('users')
    op.drop_index('ix_metadata_expires_at', table_name='metadata')
    op.drop_table('metadata')
    # ### end Alembic commands ###
